project:
  type: website

website:
  title: "Integration"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Integration-ISIK
      - icon: house-fill
        href: https://integrationfest.in
format:
  html:
    theme:
      dark: darkly
      light: flatly
    css: styles.css

execute:
  freeze: auto